name: Gradle Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/davidblm/my-gradle-image:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_PAT }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Grant execute permissions to gradlew
        run: chmod +x gradlew

      - name: Run Gradle Build
        run: ./gradlew test
        continue-on-error: true  # Prevents stopping the workflow if the build fails

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: always()  # Ensures this step runs even if the previous step fails
        with:
          name: Test Results
          path: build/reports/tests/test/
